// Code generated by protoc-gen-go. DO NOT EDIT.
// source: appinitdata.proto

package api

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// AppInitData contains the application initialization for each game.
type AppInitData struct {
	Id                   string                      `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CoreOrganizationId   string                      `protobuf:"bytes,2,opt,name=core_organization_id,json=coreOrganizationId,proto3" json:"core_organization_id,omitempty"`
	PublisherAppId       string                      `protobuf:"bytes,3,opt,name=publisher_app_id,json=publisherAppId,proto3" json:"publisher_app_id,omitempty"`
	Platform             Platform                    `protobuf:"varint,4,opt,name=platform,proto3,enum=api.Platform" json:"platform,omitempty"`
	Networks             []*AppInitData_NetworkParam `protobuf:"bytes,5,rep,name=networks,proto3" json:"networks,omitempty"`
	CreatedAt            int64                       `protobuf:"varint,6,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	Version              string                      `protobuf:"bytes,7,opt,name=version,proto3" json:"version,omitempty"`
	Coppa                bool                        `protobuf:"varint,8,opt,name=coppa,proto3" json:"coppa,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *AppInitData) Reset()         { *m = AppInitData{} }
func (m *AppInitData) String() string { return proto.CompactTextString(m) }
func (*AppInitData) ProtoMessage()    {}
func (*AppInitData) Descriptor() ([]byte, []int) {
	return fileDescriptor_64393cb37df6b336, []int{0}
}

func (m *AppInitData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppInitData.Unmarshal(m, b)
}
func (m *AppInitData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppInitData.Marshal(b, m, deterministic)
}
func (m *AppInitData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppInitData.Merge(m, src)
}
func (m *AppInitData) XXX_Size() int {
	return xxx_messageInfo_AppInitData.Size(m)
}
func (m *AppInitData) XXX_DiscardUnknown() {
	xxx_messageInfo_AppInitData.DiscardUnknown(m)
}

var xxx_messageInfo_AppInitData proto.InternalMessageInfo

func (m *AppInitData) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *AppInitData) GetCoreOrganizationId() string {
	if m != nil {
		return m.CoreOrganizationId
	}
	return ""
}

func (m *AppInitData) GetPublisherAppId() string {
	if m != nil {
		return m.PublisherAppId
	}
	return ""
}

func (m *AppInitData) GetPlatform() Platform {
	if m != nil {
		return m.Platform
	}
	return Platform_IOS
}

func (m *AppInitData) GetNetworks() []*AppInitData_NetworkParam {
	if m != nil {
		return m.Networks
	}
	return nil
}

func (m *AppInitData) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *AppInitData) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *AppInitData) GetCoppa() bool {
	if m != nil {
		return m.Coppa
	}
	return false
}

// name means "network and init params"
type AppInitData_NetworkParam struct {
	Name                 AdNetworkName     `protobuf:"varint,1,opt,name=name,proto3,enum=api.AdNetworkName" json:"name,omitempty"`
	Type                 UsageType         `protobuf:"varint,2,opt,name=type,proto3,enum=api.UsageType" json:"type,omitempty"`
	AdapterParameters    map[string]string `protobuf:"bytes,3,rep,name=adapter_parameters,json=adapterParameters,proto3" json:"adapter_parameters,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *AppInitData_NetworkParam) Reset()         { *m = AppInitData_NetworkParam{} }
func (m *AppInitData_NetworkParam) String() string { return proto.CompactTextString(m) }
func (*AppInitData_NetworkParam) ProtoMessage()    {}
func (*AppInitData_NetworkParam) Descriptor() ([]byte, []int) {
	return fileDescriptor_64393cb37df6b336, []int{0, 0}
}

func (m *AppInitData_NetworkParam) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppInitData_NetworkParam.Unmarshal(m, b)
}
func (m *AppInitData_NetworkParam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppInitData_NetworkParam.Marshal(b, m, deterministic)
}
func (m *AppInitData_NetworkParam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppInitData_NetworkParam.Merge(m, src)
}
func (m *AppInitData_NetworkParam) XXX_Size() int {
	return xxx_messageInfo_AppInitData_NetworkParam.Size(m)
}
func (m *AppInitData_NetworkParam) XXX_DiscardUnknown() {
	xxx_messageInfo_AppInitData_NetworkParam.DiscardUnknown(m)
}

var xxx_messageInfo_AppInitData_NetworkParam proto.InternalMessageInfo

func (m *AppInitData_NetworkParam) GetName() AdNetworkName {
	if m != nil {
		return m.Name
	}
	return AdNetworkName_ADMOB
}

func (m *AppInitData_NetworkParam) GetType() UsageType {
	if m != nil {
		return m.Type
	}
	return UsageType_UNKNOWN_USAGE_TYPE
}

func (m *AppInitData_NetworkParam) GetAdapterParameters() map[string]string {
	if m != nil {
		return m.AdapterParameters
	}
	return nil
}

func init() {
	proto.RegisterType((*AppInitData)(nil), "api.AppInitData")
	proto.RegisterType((*AppInitData_NetworkParam)(nil), "api.AppInitData.NetworkParam")
	proto.RegisterMapType((map[string]string)(nil), "api.AppInitData.NetworkParam.AdapterParametersEntry")
}

func init() {
	proto.RegisterFile("appinitdata.proto", fileDescriptor_64393cb37df6b336)
}

var fileDescriptor_64393cb37df6b336 = []byte{
	// 384 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x92, 0xcf, 0x6e, 0xd3, 0x40,
	0x10, 0xc6, 0x65, 0x3b, 0x6d, 0xd3, 0x09, 0x58, 0xed, 0xa8, 0x42, 0xab, 0x08, 0x24, 0xab, 0x07,
	0x64, 0x2e, 0x16, 0x0a, 0x1c, 0x80, 0x5b, 0xa4, 0x72, 0xe8, 0xa5, 0x44, 0x2b, 0x38, 0x47, 0xd3,
	0xec, 0x50, 0x56, 0x8d, 0x77, 0x47, 0xeb, 0x4d, 0x51, 0xb8, 0xf3, 0x48, 0xbc, 0x1f, 0xf2, 0x3a,
	0x84, 0x08, 0xa1, 0xde, 0x3c, 0xdf, 0xf7, 0x1b, 0xcf, 0xbf, 0x85, 0x73, 0x12, 0xb1, 0xce, 0x46,
	0x43, 0x91, 0x1a, 0x09, 0x3e, 0x7a, 0x2c, 0x48, 0xec, 0x74, 0xc2, 0x6e, 0xd3, 0x76, 0x83, 0x72,
	0xf9, 0x6b, 0x04, 0x93, 0xb9, 0xc8, 0xb5, 0xb3, 0xf1, 0x8a, 0x22, 0x61, 0x09, 0xb9, 0x35, 0x2a,
	0xab, 0xb2, 0xfa, 0x54, 0xe7, 0xd6, 0xe0, 0x6b, 0xb8, 0x58, 0xf9, 0xc0, 0x4b, 0x1f, 0xee, 0xc8,
	0xd9, 0x1f, 0x14, 0xad, 0x77, 0x4b, 0x6b, 0x54, 0x9e, 0x08, 0xec, 0xbd, 0x4f, 0x07, 0xd6, 0xb5,
	0xc1, 0x1a, 0xce, 0x64, 0x73, 0xbb, 0xb6, 0xdd, 0x37, 0x0e, 0x4b, 0x12, 0xe9, 0xe9, 0x22, 0xd1,
	0xe5, 0x5e, 0xef, 0x2b, 0x1a, 0x7c, 0x05, 0x63, 0x59, 0x53, 0xfc, 0xea, 0x43, 0xab, 0x46, 0x55,
	0x56, 0x97, 0xb3, 0xa7, 0x0d, 0x89, 0x6d, 0x16, 0x3b, 0x51, 0xef, 0x6d, 0x7c, 0x0f, 0x63, 0xc7,
	0xf1, 0xbb, 0x0f, 0xf7, 0x9d, 0x3a, 0xaa, 0x8a, 0x7a, 0x32, 0x7b, 0x91, 0xd0, 0x83, 0xd6, 0x9b,
	0x9b, 0x01, 0x58, 0x50, 0xa0, 0x56, 0xef, 0x71, 0x7c, 0x0e, 0xa7, 0xab, 0xc0, 0x14, 0xd9, 0xcc,
	0xa3, 0x3a, 0xae, 0xb2, 0xba, 0xd0, 0x7f, 0x05, 0x54, 0x70, 0xf2, 0xc0, 0xa1, 0xb3, 0xde, 0xa9,
	0x93, 0xd4, 0xe4, 0x9f, 0x10, 0x2f, 0xe0, 0x68, 0xe5, 0x45, 0x48, 0x8d, 0xab, 0xac, 0x1e, 0xeb,
	0x21, 0x98, 0xfe, 0xcc, 0xe1, 0xc9, 0x61, 0x21, 0x7c, 0x09, 0x23, 0x47, 0x2d, 0xa7, 0x95, 0x95,
	0x33, 0x1c, 0xba, 0x32, 0x3b, 0xe4, 0x86, 0x5a, 0xd6, 0xc9, 0xc7, 0x4b, 0x18, 0xc5, 0xad, 0x70,
	0x5a, 0x5c, 0x39, 0x2b, 0x13, 0xf7, 0xa5, 0xa3, 0x3b, 0xfe, 0xbc, 0x15, 0xd6, 0xc9, 0xc3, 0x15,
	0x20, 0x19, 0x92, 0xc8, 0x61, 0x29, 0xfd, 0xcf, 0x39, 0x72, 0xe8, 0x54, 0x91, 0xe6, 0x7d, 0xfb,
	0xe8, 0xbc, 0xcd, 0x7c, 0xc8, 0x5b, 0xec, 0xd3, 0x3e, 0xba, 0x18, 0xb6, 0xfa, 0x9c, 0xfe, 0xd5,
	0xa7, 0x57, 0xf0, 0xec, 0xff, 0x30, 0x9e, 0x41, 0x71, 0xcf, 0xdb, 0xdd, 0xf1, 0xfb, 0xcf, 0x7e,
	0x07, 0x0f, 0xb4, 0xde, 0xf0, 0xee, 0xdc, 0x43, 0xf0, 0x21, 0x7f, 0x97, 0xdd, 0x1e, 0xa7, 0xe7,
	0xf3, 0xe6, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0xa8, 0x3d, 0x71, 0xdf, 0x65, 0x02, 0x00, 0x00,
}
